"use client";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { grammarAnnotationAnswers, grammarAnnotationLabels } from "@/lib/grammar-definitions";
import type { GrammarAnnotation, GrammarAnnotationKind, WordClass } from "@/types";

export type GrammarInteractionKind = Exclude<GrammarAnnotationKind, "error">;
export type GrammarResponseMode = "click" | "frame" | "brackets" | "arrow";
export type GrammarInteractionDraft = { kind: GrammarInteractionKind; label: string; instruction: string; responseMode: GrammarResponseMode; nucleusWordClass: WordClass; linkedTargetId: string; visualEffect?: GrammarAnnotation["visualEffect"]; parentAnnotationId?: string; groupNucleusStart?: number; groupNucleusEnd?: number; skipGroupNucleus?: boolean; grammaticalGender?: "feminine" | "masculine"; grammaticalNumber?: "singular" | "plural"; wordClassInteractionMode?: "find_requested" | "choose_class" };
type Props = { open: boolean; draft: GrammarInteractionDraft; functionOptions: string[]; wordClassLabels: Record<WordClass, string>; kinds?: GrammarInteractionKind[]; responseModes?: GrammarResponseMode[]; answerOptions?: Partial<Record<GrammarInteractionKind, string[]>>; linkedTargetLabel?: string; selectedText?: string; showLinkedTarget?: boolean; configureVisual?: boolean; configureGroupNucleus?: boolean; groupNucleusOptions?: Array<{ start: number; end: number; text: string }>; parentOptions?: Array<{ id: string; label: string }>; onChange: (draft: GrammarInteractionDraft) => void; onCancel: () => void; onSave: () => void; onPickLinkedTarget?: () => void; onClearLinkedTarget?: () => void };

function instruction(kind: GrammarInteractionKind, label: string, mode: GrammarResponseMode) { const target = kind === "nucleus" ? "le noyau du groupe" : label.toLocaleLowerCase("fr-CA"); return mode === "arrow" ? (kind === "donor" ? `Trace une flèche de ${target} vers ses receveurs.` : `Trace une flèche du donneur vers ${target}.`) : mode === "click" ? `Clique sur ${target}.` : mode === "brackets" ? `Mets ${target} entre crochets.` : `Encadre ${target}.`; }
function initialLabel(kind: GrammarInteractionKind, wordClass: WordClass, labels: Record<WordClass, string>, options: Partial<Record<GrammarInteractionKind, string[]>>) { return options[kind]?.[0] ?? (kind === "function" ? "Sujet" : kind === "group" ? "Groupe" : kind === "gender_number" ? "Genre et nombre" : kind === "nucleus" || kind === "word_class" ? labels[wordClass] : grammarAnnotationLabels[kind]); }
function guideText(kind: GrammarInteractionKind) {
  if (kind === "group") return "Choisis le type de groupe, puis indique si le noyau doit être demandé juste après.";
  if (kind === "function") return "Choisis la fonction. Le lecteur demandera cette fonction sans mélanger les autres mécaniques.";
  if (kind === "word_class") return "Choisis si l’élève doit trouver une classe demandée ou identifier la classe du mot sélectionné.";
  if (kind === "gender_number") return "Cette étape se lie au mot déjà annoté en classe de mot : genre d’abord, nombre ensuite.";
  if (kind === "donor") return "Définis le donneur d’accord. La flèche reste une action propre aux donneurs/receveurs.";
  if (kind === "receiver") return "Définis le receveur d’accord. Tu peux le faire cliquer ou le faire relier par flèche.";
  return "Choisis la classe du noyau. Cette étape peut être liée à un groupe.";
}

export function GrammarInteractionModal({ open, draft, functionOptions, wordClassLabels, kinds = ["function", "group", "nucleus"], responseModes = ["click", "frame"], answerOptions = grammarAnnotationAnswers, linkedTargetLabel, selectedText, showLinkedTarget = true, configureVisual = false, configureGroupNucleus = false, groupNucleusOptions = [], parentOptions = [], onChange, onCancel, onSave, onPickLinkedTarget, onClearLinkedTarget }: Props) {
  if (!open) return null; const choices = draft.kind === "function" ? functionOptions : answerOptions[draft.kind] ?? [];
  const lockedKind = kinds.length === 1;
  return <div className="tree-analysis-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onCancel(); }}><aside className="tree-analysis-inspector tree-analysis-modal" role="dialog" aria-modal="true" aria-label="Créer une réponse interactive">
    <div className="tree-analysis-modal-heading"><div><span className="eyebrow">Réponse interactive</span><h3>{grammarAnnotationLabels[draft.kind]}</h3></div><button type="button" onClick={onCancel} aria-label="Fermer"><X size={18}/></button></div>
    <div className="grammar-interaction-context">
      <span>Passage sélectionné</span>
      <strong>{selectedText?.trim() || "Sélection active"}</strong>
      <p>{guideText(draft.kind)}</p>
    </div>
    <div className="grammar-interaction-step"><b>1</b><div>{lockedKind ? <label>Mécanique choisie<input value={grammarAnnotationLabels[draft.kind]} readOnly /></label> : <label>Type de réponse<select value={draft.kind} onChange={(event) => { const kind = event.target.value as GrammarInteractionKind; const label = initialLabel(kind, draft.nucleusWordClass, wordClassLabels, answerOptions); const responseMode: GrammarResponseMode = kind === "nucleus" || kind === "word_class" || kind === "gender_number" || kind === "donor" || kind === "receiver" ? "click" : responseModes.includes("brackets") ? "brackets" : "frame"; onChange({ ...draft, kind, label, responseMode, visualEffect: kind === "donor" || kind === "receiver" ? { kind: "none" } : draft.visualEffect, linkedTargetId: "", grammaticalGender: kind === "gender_number" ? draft.grammaticalGender ?? "feminine" : undefined, grammaticalNumber: kind === "gender_number" ? draft.grammaticalNumber ?? "singular" : undefined, wordClassInteractionMode: kind === "word_class" ? draft.wordClassInteractionMode ?? "find_requested" : undefined, instruction: kind === "gender_number" ? "Indique le genre, puis le nombre de ce mot." : instruction(kind, label, responseMode) }); }}>{kinds.map((kind) => <option value={kind} key={kind}>{grammarAnnotationLabels[kind]}</option>)}</select></label>}</div></div>
    <div className="grammar-interaction-step"><b>2</b><div>
    {draft.kind === "word_class" && <label>Comportement dans le lecteur<select value={draft.wordClassInteractionMode ?? "find_requested"} onChange={(event) => onChange({ ...draft, wordClassInteractionMode: event.target.value as "find_requested" | "choose_class" })}><option value="find_requested">Repérer la classe demandée — cliquer directement sur le bon mot</option><option value="choose_class">Identifier la classe du mot — cliquer sur le mot, puis choisir sa classe</option></select><small>Le deuxième mode convient lorsqu’on analyse ensuite le genre, le nombre ou les accords de ce mot.</small></label>}
    {draft.kind === "gender_number" && <div className="grammar-gender-number-fields"><label>Genre attendu<select value={draft.grammaticalGender ?? "feminine"} onChange={(event) => onChange({ ...draft, grammaticalGender: event.target.value as "feminine" | "masculine" })}><option value="feminine">Féminin — Fém.</option><option value="masculine">Masculin — Masc.</option></select></label><label>Nombre attendu<select value={draft.grammaticalNumber ?? "singular"} onChange={(event) => onChange({ ...draft, grammaticalNumber: event.target.value as "singular" | "plural" })}><option value="singular">Singulier — Sing.</option><option value="plural">Pluriel — Plur.</option></select></label><small>Le lecteur demandera toujours le genre en premier, puis le nombre.</small></div>}
    {draft.kind === "nucleus" ? <label>Classe du noyau<select value={draft.nucleusWordClass} onChange={(event) => { const nucleusWordClass = event.target.value as WordClass; onChange({ ...draft, nucleusWordClass, label: wordClassLabels[nucleusWordClass] }); }}>{(Object.keys(wordClassLabels) as WordClass[]).map((wordClass) => <option value={wordClass} key={wordClass}>{wordClassLabels[wordClass]}</option>)}</select></label> : choices.length > 0 && <label>Réponse attendue<select value={draft.label} onChange={(event) => { const label = event.target.value; onChange({ ...draft, label, instruction: instruction(draft.kind, label, draft.responseMode) }); }}>{choices.map((choice) => <option key={choice}>{choice}</option>)}</select></label>}
    {configureGroupNucleus && draft.kind === "group" && <label>Analyse du noyau<select value={draft.skipGroupNucleus ? "none" : draft.groupNucleusStart === undefined ? "" : `${draft.groupNucleusStart}:${draft.groupNucleusEnd}`} onChange={(event) => { if (event.target.value === "none") { onChange({ ...draft, skipGroupNucleus: true, groupNucleusStart: undefined, groupNucleusEnd: undefined }); return; } const [start, end] = event.target.value.split(":").map(Number); onChange({ ...draft, skipGroupNucleus: false, groupNucleusStart: Number.isFinite(start) ? start : undefined, groupNucleusEnd: Number.isFinite(end) ? end : undefined }); }}><option value="">Choisir le mot-noyau…</option><option value="none">Pas d’analyse du noyau</option>{groupNucleusOptions.map((option) => <option key={`${option.start}-${option.end}`} value={`${option.start}:${option.end}`}>{option.text}</option>)}</select><small>{draft.skipGroupNucleus ? "Le lecteur demandera seulement de délimiter et de classer ce groupe." : "Le lecteur demandera ce noyau juste après l’identification du type de groupe."}</small></label>}
    </div></div>
    <div className="grammar-interaction-step"><b>3</b><div>
    <label>Texte que l’élève verra<input value={draft.instruction} onChange={(event) => onChange({ ...draft, instruction: event.target.value })}/><small>Tu peux garder la phrase générée automatiquement ou l’adapter pour être plus clair au tableau.</small></label>
    </div></div>
    <div className="grammar-interaction-step"><b>4</b><div>
    {draft.kind !== "gender_number" && <label>Action de l’élève<select value={draft.responseMode} onChange={(event) => { const responseMode = event.target.value as GrammarResponseMode; onChange({ ...draft, responseMode, visualEffect: responseMode === "arrow" ? { kind: "none" } : draft.visualEffect, instruction: instruction(draft.kind, draft.label, responseMode) }); }}>{(draft.kind === "donor" || draft.kind === "receiver") ? <><option value="click">Cliquer sur le mot</option><option value="arrow">Tracer une flèche d’accord</option></> : <>{responseModes.includes("click") && <option value="click">Cliquer sur le mot ou le passage</option>}{responseModes.includes("frame") && <option value="frame">Tracer un encadrement</option>}{responseModes.includes("brackets") && <option value="brackets">Tracer les crochets</option>}</>}</select></label>}
    {configureVisual && draft.kind !== "gender_number" && draft.kind !== "donor" && draft.kind !== "receiver" && <><label>Résultat visuel<select value={draft.visualEffect?.kind ?? "none"} onChange={(event) => { const kind = event.target.value as NonNullable<GrammarAnnotation["visualEffect"]>["kind"]; onChange({ ...draft, visualEffect: { kind, color: ["color", "highlight", "underline"].includes(kind) ? draft.visualEffect?.color ?? "#d93434" : undefined } }); }}><option value="none">Aucune marque</option><option value="color">Texte en couleur</option><option value="frame">Encadrement</option><option value="brackets">Crochets</option><option value="bold">Gras</option><option value="highlight">Surlignage</option><option value="underline">Soulignement</option></select></label>{["color", "highlight", "underline"].includes(draft.visualEffect?.kind ?? "") && <label>Couleur<input type="color" value={draft.visualEffect?.color ?? "#d93434"} onChange={(event) => onChange({ ...draft, visualEffect: { ...draft.visualEffect!, color: event.target.value } })}/></label>}</>}
    {parentOptions.length > 0 && <label>Déclencher cette action après<select value={draft.parentAnnotationId ?? ""} onChange={(event) => onChange({ ...draft, parentAnnotationId: event.target.value || undefined })}><option value="">Aucune — action indépendante</option>{parentOptions.map((option) => <option value={option.id} key={option.id}>{option.label}</option>)}</select><small>Utile quand une action doit suivre une autre, par exemple identifier le noyau juste après un groupe.</small></label>}
    </div></div>
    {showLinkedTarget && draft.kind !== "function" && <div className="tree-analysis-linked-node-picker"><span>Rectangle déclenché (facultatif)</span><strong>{linkedTargetLabel ? `Rectangle sélectionné — ${linkedTargetLabel}` : "Aucun rectangle sélectionné"}</strong><div className="tree-analysis-modal-actions">{onPickLinkedTarget && <Button type="button" variant="secondary" onClick={onPickLinkedTarget}>Choisir dans l’arbre</Button>}{draft.linkedTargetId && onClearLinkedTarget && <Button type="button" variant="secondary" onClick={onClearLinkedTarget}>Ne lier aucun rectangle</Button>}</div></div>}
    <p>La marque et le geste sont conservés avec cet évènement et seront rejoués dans le lecteur.</p><div className="tree-analysis-modal-actions"><Button type="button" variant="secondary" onClick={onCancel}>Annuler</Button><Button type="button" onClick={onSave} disabled={!draft.label.trim() || !draft.instruction.trim() || (draft.kind === "gender_number" && (!draft.grammaticalGender || !draft.grammaticalNumber)) || (configureGroupNucleus && draft.kind === "group" && !draft.skipGroupNucleus && draft.groupNucleusStart === undefined)}>Créer l’évènement</Button></div>
  </aside></div>;
}
